contact:
    resource: "@ContactBundle/Controller/"
    type:     annotation
    prefix:   /

My:
    resource: "@UrlMyBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
